//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Server.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (8, 40)
        ///(48, 40)
        ///(128, 40)
        ///(168, 40)
        ///(208, 40)
        ///(288, 40)
        ///(328, 40)
        ///
        ///(328, 80)
        ///(288, 80)
        ///(208, 80)
        ///(168, 80)
        ///(128, 80)
        ///(48, 80)
        ///(8, 80)
        ///
        ///(328, 160)
        ///(288, 160)
        ///(208, 160)
        ///(168, 160)
        ///(128, 160)
        ///(48, 160)
        ///(8, 160)
        ///
        ///(328, 120)
        ///(288, 120)
        ///(208, 120)
        ///(168, 120)
        ///(128, 120)
        ///(48, 120)
        ///(8, 120)
        ///
        ///(88, 160)
        ///(248, 160)
        ///
        ///(248, 240)
        ///(88, 240)
        ///(328, 240)
        ///(208, 240)
        ///(168, 240)
        ///(48, 240)
        ///(8, 240)
        ///
        ///(248, 280)
        ///(88, 280)
        ///(328, 280)
        ///(208, 280)
        ///(168, 280)
        ///(48, 280)
        ///(8, 280)
        ///
        ///(248, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Coins {
            get {
                return ResourceManager.GetString("Coins", resourceCulture);
            }
        }
    }
}
